// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MiniERP.Infrastructure.Migrations
{
    [DbContext(typeof(MiniErpDbContext))]
    [Migration("20251116080642_SeedUsers")]
    partial class SeedUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.CoolingDevice", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Id"), "utf8mb4");

                    b.Property<int>("DeviceType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("WarehouseId")
                        .HasColumnType("varchar(255)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("WarehouseId"), "utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Domain.Entities.DeviceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceId")
                        .HasColumnType("varchar(255)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("DeviceId"), "utf8mb4");

                    b.Property<double>("Humidity")
                        .HasColumnType("double");

                    b.Property<double>("Temperature")
                        .HasColumnType("double");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("DeviceLogs");
                });

            modelBuilder.Entity("Domain.Entities.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "TQ",
                            Name = "Tuyên Quang"
                        },
                        new
                        {
                            Id = 2,
                            Code = "LC",
                            Name = "Lào Cai"
                        },
                        new
                        {
                            Id = 3,
                            Code = "TNG",
                            Name = "Thái Nguyên"
                        },
                        new
                        {
                            Id = 4,
                            Code = "PT",
                            Name = "Phú Thọ"
                        },
                        new
                        {
                            Id = 5,
                            Code = "BN",
                            Name = "Bắc Ninh"
                        },
                        new
                        {
                            Id = 6,
                            Code = "HY",
                            Name = "Hưng Yên"
                        },
                        new
                        {
                            Id = 7,
                            Code = "HP",
                            Name = "Hải Phòng"
                        },
                        new
                        {
                            Id = 8,
                            Code = "NB",
                            Name = "Ninh Bình"
                        },
                        new
                        {
                            Id = 9,
                            Code = "QT",
                            Name = "Quảng Trị"
                        },
                        new
                        {
                            Id = 10,
                            Code = "DAN",
                            Name = "Đà Nẵng"
                        },
                        new
                        {
                            Id = 11,
                            Code = "QNG",
                            Name = "Quảng Ngãi"
                        },
                        new
                        {
                            Id = 12,
                            Code = "GL",
                            Name = "Gia Lai"
                        },
                        new
                        {
                            Id = 13,
                            Code = "KH",
                            Name = "Khánh Hòa"
                        },
                        new
                        {
                            Id = 14,
                            Code = "LD",
                            Name = "Lâm Đồng"
                        },
                        new
                        {
                            Id = 15,
                            Code = "DLK",
                            Name = "Đắk Lắk"
                        },
                        new
                        {
                            Id = 16,
                            Code = "HCM",
                            Name = "Hồ Chí Minh"
                        },
                        new
                        {
                            Id = 17,
                            Code = "DNI",
                            Name = "Đồng Nai"
                        },
                        new
                        {
                            Id = 18,
                            Code = "TNI",
                            Name = "Tây Ninh"
                        },
                        new
                        {
                            Id = 19,
                            Code = "CT",
                            Name = "Cần Thơ"
                        },
                        new
                        {
                            Id = 20,
                            Code = "VL",
                            Name = "Vĩnh Long"
                        },
                        new
                        {
                            Id = 21,
                            Code = "DTP",
                            Name = "Đồng Tháp"
                        },
                        new
                        {
                            Id = 22,
                            Code = "CM",
                            Name = "Cà Mau"
                        },
                        new
                        {
                            Id = 23,
                            Code = "AG",
                            Name = "An Giang"
                        },
                        new
                        {
                            Id = 24,
                            Code = "HN",
                            Name = "Hà Nội"
                        },
                        new
                        {
                            Id = 25,
                            Code = "HUE",
                            Name = "Huế"
                        },
                        new
                        {
                            Id = 26,
                            Code = "LCH",
                            Name = "Lai Châu"
                        },
                        new
                        {
                            Id = 27,
                            Code = "DB",
                            Name = "Điện Biên"
                        },
                        new
                        {
                            Id = 28,
                            Code = "SL",
                            Name = "Sơn La"
                        },
                        new
                        {
                            Id = 29,
                            Code = "LS",
                            Name = "Lạng Sơn"
                        },
                        new
                        {
                            Id = 30,
                            Code = "QNI",
                            Name = "Quảng Ninh"
                        },
                        new
                        {
                            Id = 31,
                            Code = "TH",
                            Name = "Thanh Hóa"
                        },
                        new
                        {
                            Id = 32,
                            Code = "NA",
                            Name = "Nghệ An"
                        },
                        new
                        {
                            Id = 33,
                            Code = "HT",
                            Name = "Hà Tĩnh"
                        },
                        new
                        {
                            Id = 34,
                            Code = "CB",
                            Name = "Cao Bằng"
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 16, 8, 6, 41, 662, DateTimeKind.Utc).AddTicks(2755),
                            Email = "admin@minierp.com",
                            FullName = "Administrator",
                            IsActive = true,
                            PasswordHash = "$2a$11$msJFBe5lFbiL0TjKIM1IE.Zsa6REwc7H.pQHCmfBWfZNEpt4IvhZW",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 16, 8, 6, 41, 815, DateTimeKind.Utc).AddTicks(6779),
                            Email = "user1@minierp.com",
                            FullName = "Nguyễn Văn A",
                            IsActive = true,
                            PasswordHash = "$2a$11$TcyIkGxO3vGRZE52wzFbM.gn1LE38MfO7Tg.fUAA1JJtG6AJ.lOoW",
                            Username = "user1"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 16, 8, 6, 41, 966, DateTimeKind.Utc).AddTicks(7618),
                            Email = "user2@minierp.com",
                            FullName = "Trần Thị B",
                            IsActive = true,
                            PasswordHash = "$2a$11$/PF5vrHiDfX1.ATSziaxH.MFVsdkvZy/G8XFoDiR4yQSnS75wYpTO",
                            Username = "user2"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Warehouse", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("Domain.Entities.CoolingDevice", b =>
                {
                    b.HasOne("Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Domain.Entities.DeviceLog", b =>
                {
                    b.HasOne("Domain.Entities.CoolingDevice", "Device")
                        .WithMany("Logs")
                        .HasForeignKey("DeviceId");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Domain.Entities.Warehouse", b =>
                {
                    b.HasOne("Domain.Entities.Province", "Province")
                        .WithMany("Warehouses")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Domain.Entities.CoolingDevice", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("Domain.Entities.Province", b =>
                {
                    b.Navigation("Warehouses");
                });
#pragma warning restore 612, 618
        }
    }
}
